### ISSUE TITLE
HTTPS support for the editor website

### ISSUE THREAD

**Issue by ferrata** [magjac/graphviz-visual-editor#178]
It would be great to have HTTPS supported on the http://magjac.com/graphviz-visual-editor website.

**Comment by magjac** [comment]
Thanks for the proposal. I don't think this is not something that this application need to be aware of. It's a matter for the http://magjac.com server. I'll leave it open though, since I'm managing both and easy forgets about things.

**Comment by ferdnyc** [comment]
@magjac Just pinging this issue again, since browsers are increasingly making it harder to connect to HTTP servers without jumping through hoops. Plus, these days [Let's Encrypt](https://letsencrypt.org/) provides a free, practically frictionless path to enabling HTTPS support for basically any site. Heck, even my home server has it enabled, and that serves nothing but a few of my personal files to a sole audience of me.

**Comment by magjac** [comment]
The editor now runs at https://magjac.com/graphviz-visual-editor/
