### ISSUE TITLE
Issue about Cluster Nodes

### ISSUE THREAD

**Issue by Heidernlee** [magjac/graphviz-visual-editor#180]
Hello again.

I am however stuck on an issue regarding clustered nodes. 
It's about draw an arrow from child-node to its parent
Like this:
![HeidernExample2](https://user-images.githubusercontent.com/25810034/143977199-cbe5b627-fa64-425a-8806-92a2e1e6d8a7.png)

I've tried draw an arrow from [GOTO-CALL] to [Layer2] ,
but a new node appeared..... It is a bug ?

Thanks.

**Comment by magjac** [comment]
I've moved this issue from [d3-graphviz](https://github.com/magjac/d3-graphviz) to here since it's apparently related to the drawing function of the visual editor.

I cannot reproduce this problem. Right-clicking `GOTO-CALL` starts the drawing function (correctly) but trying to finish it by double-clicking `Layer3` does not finish it (also correctly since Layer3 is not a node).

@Heidernlee Can you describe the exact steps that you did to trigger this problem.

**Comment by magjac** [comment]
Closing due to lack of response. Feel free to get back with more info and I will look into it.
